### ISSUE TITLE
Render form validation errors on Login form

### ISSUE THREAD

**Issue by czmud** [czmud/adventureConnect#27]
Currently, errors are being returned through state variable 'errors' but are not being rendered on login form. Login fails, but users are given no explanation as to why they were unable to login.

errors are returned as an error list:

```ts
errors = [
{path: "email", message:"Account for this email does not exist"}
{path: "", message:""}
//...etc
]
```

parse errors and render them adjacent to their respective fields, using Materials UI to render.

**Comment by czmud** [comment]
@GreenJ84 asked:

We have errors in arrays which makes it hard to directly relate to form fields (have to get by index or mapping in one box). But if we change it to an object, I could directly render the errors
```
errors = {
(path): (message),
email: 'Not a valid email',
 ...etc
}
```
what you think?

**Comment by czmud** [comment]
Yeah, I'm good with it!

What do you think about keeping this format instead. That way were more consistent with the format that Mongoose generates the errors in:

```ts
errors = {
    email: { 
        path: "email",
        message: "Account for this email does not exist"
}}
```

**Comment by GreenJ84** [comment]
Definitely love the new method for recording Errors in State! If you complete and make sure errors all finalize in the format, I can implement the errors on the front end with the message and styling changes  to the elements.

**Comment by czmud** [comment]
Sounds good, I just opened a pull request to update the new format of these errors. #40
