### ISSUE TITLE
Add ternary statements to only show logout buttons when organizer is logged in

### ISSUE THREAD

**Issue by czmud** [czmud/adventureConnect#32]
Saw this on the event view page, but may exist elsewhere.

<img width="1217" alt="Screen Shot 2022-10-11 at 19 00 58" src="https://user-images.githubusercontent.com/91854538/195231563-db4b365c-2386-4ce0-93e8-467f5ec5fdbe.png">

**Comment by GreenJ84** [comment]
This issue's fix was added with PR #54
