### ISSUE TITLE
Fix HTML DOM nesting errors on Create Event Page

### ISSUE THREAD

**Issue by czmud** [czmud/adventureConnect#41]
Multiple html erros log on the console when loading Create Event Page:
- <form> as descendant <p>
- <p> as descendant of <p>
- <div> as descendant of <p>
- <fieldset> as descendant of <p>
- issue with "z-Index" prop (maybe this should be "z-index" instead?)

![Screen Shot 2022-10-12 at 21 21 30](https://user-images.githubusercontent.com/91854538/195501285-de98727a-0fd1-4d29-be7f-ab6a0aaa7e81.png)

**Comment by GreenJ84** [comment]
This issue's fix was added in PR #54
